name: hanzishu
description: Hanzishu project using new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: "^0.4.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  flutter_tts:

  json_annotation: ^3.0.0

  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/charactertree.png
     - assets/characterlist.png
     - assets/breakout.png
     - assets/conversations.png
     - assets/quiz.png
     - assets/components/LC11.png
     - assets/components/LC12.png
     - assets/components/LC13.png
     - assets/components/LC14.png
     - assets/components/LC15.png
     - assets/components/LC21.png
     - assets/components/LC22.png
     - assets/components/LC23.png
     - assets/components/LC24.png
     - assets/components/LC25.png
     - assets/components/LC31.png
     - assets/components/LC32.png
     - assets/components/LC33.png
     - assets/components/LC34.png
     - assets/components/LC35.png
     - assets/components/LC41.png
     - assets/components/LC42.png
     - assets/components/LC43.png
     - assets/components/LC44.png
     - assets/components/LC51.png
     - assets/components/LC52.png
     - assets/components/LC53.png
     - assets/components/LC54.png
     - assets/components/LC55.png
     - assets/components/LC61.png
     - assets/components/LC62.png
     - assets/letters/L11.png
     - assets/letters/L12.png
     - assets/letters/L13.png
     - assets/letters/L14.png
     - assets/letters/L15.png
     - assets/letters/L21.png
     - assets/letters/L22.png
     - assets/letters/L23.png
     - assets/letters/L24.png
     - assets/letters/L25.png
     - assets/letters/L31.png
     - assets/letters/L32.png
     - assets/letters/L33.png
     - assets/letters/L34.png
     - assets/letters/L35.png
     - assets/letters/L41.png
     - assets/letters/L42.png
     - assets/letters/L43.png
     - assets/letters/L44.png
     - assets/letters/L51.png
     - assets/letters/L52.png
     - assets/letters/L53.png
     - assets/letters/L54.png
     - assets/letters/L55.png
     - assets/letters/L61.png
     - assets/letters/L62.png
     - assets/letters/LG1.png
     - assets/letters/LG2.png
     - assets/letters/LG3.png
     - assets/letters/LG4.png
     - assets/letters/LG5.png
     - assets/letters/LG6.png
     - assets/typing/C00.png
     - assets/typing/C11.png
     - assets/typing/C12.png
     - assets/typing/C13.png
     - assets/typing/C14.png
     - assets/typing/C15.png
     - assets/typing/C21.png
     - assets/typing/C22.png
     - assets/typing/C23.png
     - assets/typing/C24.png
     - assets/typing/C25.png
     - assets/typing/C31.png
     - assets/typing/C32.png
     - assets/typing/C33.png
     - assets/typing/C34.png
     - assets/typing/C35.png
     - assets/typing/C41.png
     - assets/typing/C42.png
     - assets/typing/C43.png
     - assets/typing/C44.png
     - assets/typing/C51.png
     - assets/typing/C52.png
     - assets/typing/C53.png
     - assets/typing/C54.png
     - assets/typing/C61.png
     - assets/typing/C62.png
     - assets/typing/E11.png
     - assets/typing/E12.png
     - assets/typing/E13.png
     - assets/typing/E14.png
     - assets/typing/E15.png
     - assets/typing/E21.png
     - assets/typing/E22.png
     - assets/typing/E23.png
     - assets/typing/E24.png
     - assets/typing/E25.png
     - assets/typing/E31.png
     - assets/typing/E32.png
     - assets/typing/E33.png
     - assets/typing/E34.png
     - assets/typing/E35.png
     - assets/typing/E41.png
     - assets/typing/E42.png
     - assets/typing/E43.png
     - assets/typing/E44.png
     - assets/typing/E51.png
     - assets/typing/E52.png
     - assets/typing/E53.png
     - assets/typing/E54.png
     - assets/typing/E61.png
     - assets/typing/E62.png
     - assets/typing/EF11.png
     - assets/typing/EF12.png
     - assets/typing/EF13.png
     - assets/typing/EF14.png
     - assets/typing/EF15.png
     - assets/typing/EF21.png
     - assets/typing/EF22.png
     - assets/typing/EF23.png
     - assets/typing/EF24.png
     - assets/typing/EF25.png
     - assets/typing/EF31.png
     - assets/typing/EF32.png
     - assets/typing/EF33.png
     - assets/typing/EF34.png
     - assets/typing/EF35.png
     - assets/typing/EF41.png
     - assets/typing/EF42.png
     - assets/typing/EF43.png
     - assets/typing/EF44.png
     - assets/typing/EF51.png
     - assets/typing/EF52.png
     - assets/typing/EF53.png
     - assets/typing/EF54.png
     - assets/typing/EF61.png
     - assets/typing/EF62.png
     - assets/typing/EF24Sample.png
     - assets/typing/EF33Sample.png
     - assets/typing/G1.png
     - assets/typing/G2.png
     - assets/typing/G3.png
     - assets/typing/G4.png
     - assets/typing/G5.png
     - assets/typing/G6.png
     - assets/typing/GG1.png
     - assets/typing/GG2.png
     - assets/typing/GG3.png
     - assets/typing/GG4.png
     - assets/typing/GG5.png
     - assets/typing/GG6.png
     - assets/typing/GN1.png
     - assets/typing/GN2.png
     - assets/typing/GN3.png
     - assets/typing/GN4.png
     - assets/typing/GN5.png
     - assets/typing/GN6.png
     - assets/typing/EF33.png
     - assets/typing/FullComponents.png
     - assets/typing/Strokes.png
     - assets/typingexercise/450.png
     - assets/typingexercise/451.png
     - assets/typingexercise/452.png
     - assets/typingexercise/453.png
     - assets/typingexercise/454.png
     - assets/typingexercise/455.png
     - assets/typingexercise/456.png
     - assets/typingexercise/457.png
     - assets/typingexercise/458.png
     - assets/typingexercise/459.png
     - assets/typingexercise/460.png
     - assets/typingexercise/461.png
     - assets/typingexercise/462.png
     - assets/typingexercise/463.png
     - assets/typingexercise/464.png
     - assets/typingexercise/465.png
     - assets/typingexercise/466.png
     - assets/typingexercise/467.png
     - assets/typingexercise/468.png
     - assets/typingexercise/469.png
     - assets/typingexercise/470.png
     - assets/typingexercise/471.png
     - assets/typingexercise/488.png
     - assets/typingexercise/489.png
     - assets/typingexercise/490.png
     - assets/typingexercise/491.png
     - assets/typingexercise/492.png
     - assets/typingexercise/493.png
     - assets/typingexercise/494.png
     - assets/typingexercise/495.png
     - assets/typingexercise/496.png
     - assets/typingexercise/497.png
     - assets/typingexercise/498.png
     - assets/typingexercise/499.png
     - assets/typingexercise/500.png
     - assets/typingexercise/501.png
     - assets/typingexercise/502.png
     - assets/typingexercise/503.png
     - assets/typingexercise/504.png
     - assets/typingexercise/505.png
     - assets/typingexercise/506.png
     - assets/typingexercise/507.png
     - assets/typingexercise/508.png
     - assets/typingexercise/509.png
     - assets/typingexercise/510.png
     - assets/typingexercise/511.png
     - assets/typingexercise/512.png
     - assets/typingexercise/513.png
     - assets/typingexercise/514.png
     - assets/typingexercise/515.png
     - assets/typingexercise/516.png
     - assets/typingexercise/517.png
     - assets/typingexercise/518.png
     - assets/typingexercise/519.png
     - assets/IMG_6604.JPG
     - assets/IMG_6606.PNG
     - assets/lessons/L0.png
     - assets/lessons/L1.png
     - assets/lessons/L2.png
     - assets/lessons/L3.png
     - assets/lessons/L4.png
     - assets/lessons/L5.png
     - assets/lessons/L6.png
     - assets/lessons/L7.png
     - assets/lessons/L8.png
     - assets/lessons/L9.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
